services:
  - type: web
    name: webhook-delivery-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: webhook-delivery-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: webhook-delivery-redis
          type: redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: webhook-delivery-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: webhook-delivery-redis
          type: redis
          property: connectionString
      - key: APP_SECRET_KEY
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: LOG_RETENTION_HOURS
        value: "72"
      - key: MAX_RETRY_ATTEMPTS
        value: "5"

databases:
  - name: webhook-delivery-db
    databaseName: webhook_delivery
    user: webhook_delivery
    plan: free

redis:
  - name: webhook-delivery-redis
    plan: free 